name: resapp
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.20.0
  font_awesome_flutter: ^10.7.0
  flutter_local_notifications: ^17.1.2
  flutter_plugin_android_lifecycle: ^2.0.17
  webview_flutter: ^4.8.0
  google_sign_in: ^6.1.6
  firebase_auth: ^4.12.0
  cloud_firestore: ^4.13.2
  provider: ^6.1.1
  image_picker: ^1.0.4
  file_picker: ^8.0.0+1
  firebase_storage: ^11.5.5
  intl: ^0.18.1
  google_fonts: 6.1.0
  cupertino_icons: ^1.0.2
  firebase_messaging: ^14.9.4
  rxdart: ^0.27.7
  uuid: ^4.3.3
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.1
  url_launcher: ^6.2.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/appimages/rescom.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/appimages/rescom.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  flutter_lints: ^3.0.0
flutter:
 
  uses-material-design: true
  assets:
    - assets/appimages/pp.png
