// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1euFfjY4JZoQuXMcL25xRSsVYv6jFw8Q',
    appId: '1:999803465068:web:d27027256ffaaa0cb39749',
    messagingSenderId: '999803465068',
    projectId: 'resapp-9b431',
    authDomain: 'resapp-9b431.firebaseapp.com',
    storageBucket: 'resapp-9b431.appspot.com',
    measurementId: 'G-PFTE8FGQ8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw1-5d20PMQqE9PMbaoCklA3wHM4zoK-8',
    appId: '1:999803465068:android:19b1d867e2217880b39749',
    messagingSenderId: '999803465068',
    projectId: 'resapp-9b431',
    storageBucket: 'resapp-9b431.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoLgrJde9ITQcLHBaNNsmazRsTxpfty1o',
    appId: '1:999803465068:ios:2f87cd3ed7d1b1b7b39749',
    messagingSenderId: '999803465068',
    projectId: 'resapp-9b431',
    storageBucket: 'resapp-9b431.appspot.com',
    iosBundleId: 'com.example.resapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoLgrJde9ITQcLHBaNNsmazRsTxpfty1o',
    appId: '1:999803465068:ios:2f87cd3ed7d1b1b7b39749',
    messagingSenderId: '999803465068',
    projectId: 'resapp-9b431',
    storageBucket: 'resapp-9b431.appspot.com',
    iosBundleId: 'com.example.resapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1euFfjY4JZoQuXMcL25xRSsVYv6jFw8Q',
    appId: '1:999803465068:web:31957daab307b7d4b39749',
    messagingSenderId: '999803465068',
    projectId: 'resapp-9b431',
    authDomain: 'resapp-9b431.firebaseapp.com',
    storageBucket: 'resapp-9b431.appspot.com',
    measurementId: 'G-2WGV9HG6XL',
  );
}
