class ResearchTopic {
  final String id;
  final String title;
  bool isSelected;

  ResearchTopic({
    required this.id,
    required this.title,
    this.isSelected = false,
  });
}

List<ResearchTopic> researchTopics = [
  ResearchTopic(id: '77', title: 'Blockchain'),
  ResearchTopic(id: '78', title: 'Business'),
  ResearchTopic(id: '79', title: 'Art'),
  ResearchTopic(id: '80', title: 'Entreprenuership'),
  ResearchTopic(id: '1', title: 'Women'),
  ResearchTopic(id: '2', title: 'Parenting'),
  ResearchTopic(id: '3', title: 'Plastic Surgery'),
  ResearchTopic(id: '4', title: 'Prostitution'),
  ResearchTopic(id: '5', title: 'LGBT '),
  ResearchTopic(id: '6', title: 'LGBTQIA+'),
  ResearchTopic(id: '7', title: 'Social Media Influencers'),
  ResearchTopic(id: '8', title: 'Sex and Sexuality'),
  ResearchTopic(id: '9', title: 'Female Athletes'),
  ResearchTopic(id: '10', title: 'Traditional Wife'),
  ResearchTopic(id: '11', title: 'Violence and Rape'),
  ResearchTopic(id: '12', title: "Women's Rights"),
  ResearchTopic(id: '13', title: 'Birth Control and Pregnancy'),
  ResearchTopic(id: '14', title: 'Body Image'),
  ResearchTopic(id: '15', title: 'Terrorism'),
  ResearchTopic(id: '16', title: 'Politics in Social Media Era'),
  ResearchTopic(id: '17', title: 'Blockchain and Cryptocurrency'),
  ResearchTopic(id: '18', title: 'FTX Cryptocurrency Exchange'),
  ResearchTopic(id: '19', title: 'Innovation in AI and Machine Learning'),
  ResearchTopic(id: '20', title: 'Quantum Computing'),
  ResearchTopic(id: '21', title: 'Smart Cities '),
  ResearchTopic(id: '22', title: 'The Future of Social Media'),
  ResearchTopic(id: '23', title: 'Suicide'),
  ResearchTopic(id: '24', title: 'Buddhism'),
  ResearchTopic(id: '25', title: 'Cults'),
  ResearchTopic(id: '26', title: 'Christianity'),
  ResearchTopic(id: '27', title: 'Freedom of Religion'),
  ResearchTopic(id: '28', title: 'Occultism'),
  ResearchTopic(id: '31', title: 'Hinduism'),
  ResearchTopic(id: '32', title: 'Islam'),
  ResearchTopic(id: '33', title: 'Judaism'),
  ResearchTopic(id: '34', title: 'Meditation'),
  ResearchTopic(id: '36', title: 'Religious Fundamentalism'),
  ResearchTopic(id: '37', title: 'Scientology'),
  ResearchTopic(id: '38', title: 'Taoism'),
  ResearchTopic(id: '40', title: 'Religion'),
  ResearchTopic(id: '41', title: 'Psychology'),
  ResearchTopic(id: '42', title: 'Taxes'),
  ResearchTopic(id: '43', title: 'AIDS'),
  ResearchTopic(id: '44', title: 'Cancer'),
  ResearchTopic(id: '45', title: 'Coronavirus (COVID-19)'),
  ResearchTopic(id: '46', title: 'Depression'),
  ResearchTopic(id: '47', title: 'Autism'),
  ResearchTopic(id: '48', title: 'Obesity'),
  ResearchTopic(id: '49', title: 'Mental Health'),
  ResearchTopic(id: '50', title: 'Family Issues'),
  ResearchTopic(id: '51', title: 'Environmental Energy'),
  ResearchTopic(id: '52', title: 'Education'),
  ResearchTopic(id: '53', title: 'Sex Education'),
  ResearchTopic(id: '54', title: 'Literacy'),
  ResearchTopic(id: '55', title: 'Standardized Tests'),
  ResearchTopic(id: '56', title: 'Drugs'),
  ResearchTopic(id: '57', title: 'Alcohol'),
  ResearchTopic(id: '58', title: 'Crime, Law, and Social Justice'),
  ResearchTopic(id: '59', title: 'Cloud Computing'),
  ResearchTopic(id: '60', title: 'Cybersecurity'),
  ResearchTopic(id: '61', title: 'E-business'),
  ResearchTopic(id: '62', title: 'Machine Learning and Automation'),
  ResearchTopic(id: '63', title: 'Technology'),
  ResearchTopic(id: '64', title: 'Electronics'),
  ResearchTopic(id: '65', title: 'Communication'),
  ResearchTopic(id: '66', title: 'Computer Science'),
  ResearchTopic(id: '67', title: 'AI'),
  ResearchTopic(id: '68', title: 'Marketing and Advertising'),
  ResearchTopic(id: '69', title: 'Sales'),
  ResearchTopic(id: '70', title: 'Customer Service'),
  ResearchTopic(id: '71', title: 'Finance'),
  ResearchTopic(id: '72', title: 'Economics'),
  ResearchTopic(id: '73', title: 'Construction'),
  ResearchTopic(id: '74', title: 'Gaming'),
  ResearchTopic(id: '75', title: 'Programming'),
  ResearchTopic(id: '76', title: 'Robotics'),
];
