name: Flutter CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Adjusted to use Java 11
          distribution: 'temurin'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.19.0  # Adjusted to use stable channel

      - name: Get latest build number
        id: get_build_number
        run: echo "::set-output name=build_number::$(expr $(ls build/app/outputs/apk/release/app-release-*.apk 2>/dev/null | wc -l) + 1)"

      - name: Flutter pub get
        run: flutter pub get

      - name: Flutter build APK
        run: flutter build apk --release  # Adjusted to build release APK

      
